test_projects = {
    "response_data": [
        {
            "id": 8,
            "name": "Hélène",
            "description": "Some sample forms for me and others! Yay!",
            "archived": None,
            "keyId": None,
            "createdAt": "2021-02-15T01:19:41.923Z",
            "updatedAt": "2022-07-07T23:39:39.198Z",
            "deletedAt": None,
            "verbs": [
                "project.read",
                "form.list",
                "form.read",
                "submission.read",
                "submission.list",
            ],
        },
        {
            "id": 51,
            "name": "Lindsay",
            "description": None,
            "archived": None,
            "keyId": None,
            "createdAt": "2022-07-07T23:40:16.722Z",
            "updatedAt": None,
            "deletedAt": None,
            "verbs": [
                "project.read",
                "project.update",
                "project.delete",
                "form.create",
                "form.delete",
                "form.list",
                "form.read",
                "form.update",
                "submission.create",
                "submission.read",
                "submission.list",
                "submission.update",
                "field_key.create",
                "field_key.delete",
                "field_key.list",
                "assignment.list",
                "assignment.create",
                "assignment.delete",
                "public_link.create",
                "public_link.list",
                "public_link.read",
                "public_link.update",
                "public_link.delete",
                "session.end",
                "submission.update",
                "form.restore",
            ],
        },
    ]
}
project_app_users = {
    "project_id": 1,
    "response_data": [
        {
            "projectId": 1,
            "id": 115,
            "type": "field_key",
            "displayName": "test_user_1",
            "createdAt": "2018-04-18T23:19:14.802Z",
            "updatedAt": None,
            "deletedAt": None,
            "token": "d1!E2GVHgpr4h9bpxxtqUJ7EVJ1Q$Dusm2RBXg8XyVJMCBCbvyE8cGacxUx3bcUT",
        },
        {
            "projectId": 1,
            "id": 116,
            "type": "field_key",
            "displayName": "test_user_2",
            "createdAt": "2018-04-18T23:23:14.802Z",
            "updatedAt": None,
            "deletedAt": None,
            "token": None,
        },
    ],
}
roles = {
    "response_data": [
        {
            "id": 6,
            "name": "Project Viewer",
            "system": "viewer",
            "createdAt": None,
            "updatedAt": None,
            "verbs": [
                "project.read",
                "form.list",
                "form.read",
                "submission.read",
                "submission.list",
                "dataset.list",
                "entity.list",
            ],
        },
        {
            "id": 3,
            "name": "Password Reset Token",
            "system": "pwreset",
            "createdAt": "2022-10-06T16:39:20.979Z",
            "updatedAt": None,
            "verbs": ["user.password.reset"],
        },
        {
            "id": 2,
            "name": "App User",
            "system": "app-user",
            "createdAt": "2022-10-06T16:39:20.939Z",
            "updatedAt": None,
            "verbs": ["form.read", "submission.create"],
        },
        {
            "id": 7,
            "name": "Form Viewer (system internal)",
            "system": "formview",
            "createdAt": None,
            "updatedAt": None,
            "verbs": ["form.read"],
        },
        {
            "id": 8,
            "name": "Data Collector",
            "system": "formfill",
            "createdAt": None,
            "updatedAt": None,
            "verbs": ["project.read", "form.list", "form.read", "submission.create"],
        },
        {
            "id": 9,
            "name": "Public Link",
            "system": "pub-link",
            "createdAt": "2022-10-06T16:39:21.445Z",
            "updatedAt": None,
            "verbs": ["form.read", "submission.create"],
        },
        {
            "id": 1,
            "name": "Administrator",
            "system": "admin",
            "createdAt": "2022-10-06T16:39:20.939Z",
            "updatedAt": None,
            "verbs": [
                "config.read",
                "field_key.create",
                "field_key.delete",
                "field_key.list",
                "form.create",
                "form.delete",
                "form.list",
                "form.read",
                "form.update",
                "project.create",
                "project.delete",
                "project.read",
                "project.update",
                "session.end",
                "submission.create",
                "submission.read",
                "submission.list",
                "user.create",
                "user.list",
                "user.password.invalidate",
                "user.read",
                "user.update",
                "submission.update",
                "role.create",
                "role.update",
                "role.delete",
                "assignment.list",
                "assignment.create",
                "assignment.delete",
                "user.delete",
                "audit.read",
                "public_link.create",
                "public_link.list",
                "public_link.read",
                "public_link.update",
                "public_link.delete",
                "backup.run",
                "submission.update",
                "config.set",
                "analytics.read",
                "form.restore",
                "dataset.list",
                "entity.list",
            ],
        },
        {
            "id": 5,
            "name": "Project Manager",
            "system": "manager",
            "createdAt": None,
            "updatedAt": None,
            "verbs": [
                "project.read",
                "project.update",
                "project.delete",
                "form.create",
                "form.delete",
                "form.list",
                "form.read",
                "form.update",
                "submission.create",
                "submission.read",
                "submission.list",
                "submission.update",
                "field_key.create",
                "field_key.delete",
                "field_key.list",
                "assignment.list",
                "assignment.create",
                "assignment.delete",
                "public_link.create",
                "public_link.list",
                "public_link.read",
                "public_link.update",
                "public_link.delete",
                "session.end",
                "submission.update",
                "form.restore",
                "dataset.list",
                "entity.list",
            ],
        },
    ]
}
