test_projects = {
    "response_data": [
        {
            "id": 8,
            "name": "Hélène",
            "description": "Some sample forms for me and others! Yay!",
            "archived": None,
            "keyId": None,
            "createdAt": "2021-02-15T01:19:41.923Z",
            "updatedAt": "2022-07-07T23:39:39.198Z",
            "deletedAt": None,
            "verbs": [
                "project.read",
                "form.list",
                "form.read",
                "submission.read",
                "submission.list",
            ],
        },
        {
            "id": 51,
            "name": "Lindsay",
            "description": None,
            "archived": None,
            "keyId": None,
            "createdAt": "2022-07-07T23:40:16.722Z",
            "updatedAt": None,
            "deletedAt": None,
            "verbs": [
                "project.read",
                "project.update",
                "project.delete",
                "form.create",
                "form.delete",
                "form.list",
                "form.read",
                "form.update",
                "submission.create",
                "submission.read",
                "submission.list",
                "submission.update",
                "field_key.create",
                "field_key.delete",
                "field_key.list",
                "assignment.list",
                "assignment.create",
                "assignment.delete",
                "public_link.create",
                "public_link.list",
                "public_link.read",
                "public_link.update",
                "public_link.delete",
                "session.end",
                "submission.update",
                "form.restore",
            ],
        },
    ]
}
